# Generated by Django 4.1.3 on 2022-11-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_delete_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Satff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=100)),
            ],
        ),
    ]
