# Generated by Django 4.1.3 on 2022-11-13 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_satff'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Satff',
            new_name='Staff',
        ),
    ]
